'use client'

import {TopNavbar} from '@/components/layout/TopNavbar'
import '../globals.css'
import { Inter } from 'next/font/google'
import { LeftNavbar } from '@/components/layout/LeftNavbar'
import { FooterNavbar } from '@/components/layout/FooterNavbar'
import { MenuProvider } from '@/context/MenuContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <MenuProvider>
    <html lang="es">
      <body className={`${inter.className}`}>
        
        <TopNavbar />
        <div className="flex overflow-hidden bg-white pt-16">
       
          <LeftNavbar />
        
        </div>
        
        <main className='w-full md:pl-52 overflow-hidden'>
          <div className='m-auto max-w-7xl p-5 bg-red-600'>
            {children}
          </div>
         </main>
        <FooterNavbar />
        <div className="bg-gray-900 opacity-50 hidden fixed inset-0 z-10" id="sidebarBackdrop"></div>
      <div id="main-content" className="h-full w-full bg-gray-50 relative overflow-y-auto lg:ml-64">
         
      </div>
      </body>
    </html>
    </MenuProvider>
  )
}
