export const paises = [
  { name: "España" },
  { name: "Albania" },
  { name: "Alemania" },
  { name: "Andorra" },
  { name: "Armenia" },
  { name: "Austria" },
  { name: "Azerbaiyán" },
  { name: "Bélgica" },
  { name: "Bielorrusia" },
  { name: "Bosnia y Herzegovina" },
  { name: "Bulgaria" },
  { name: "Chipre" },
  { name: "Ciudad del Vaticano" },
  { name: "Croacia" },
  { name: "Dinamarca" },
  { name: "Eslovaquia" },
  { name: "Eslovenia" },
  { name: "Estonia" },
  { name: "Finlandia" },
  { name: "Francia" },
  { name: "Georgia" },
  { name: "Grecia" },
  { name: "Hungría" },
  { name: "Irlanda" },
  { name: "Islandia" },
  { name: "Italia" },
  { name: "Kazajistán" },
  { name: "Letonia" },
  { name: "Liechtenstein" },
  { name: "Lituania" },
  { name: "Luxemburgo" },
  { name: "Macedonia del Norte" },
  { name: "Malta" },
  { name: "Moldavia" },
  { name: "Mónaco" },
  { name: "Montenegro" },
  { name: "Noruega" },
  { name: "Países Bajos" },
  { name: "Polonia" },
  { name: "Portugal" },
  { name: "Reino Unido" },
  { name: "República Checa" },
  { name: "Rumanía" },
  { name: "Rusia" },
  { name: "San Marino" },
  { name: "Serbia" },
  { name: "Suecia" },
  { name: "Suiza" },
  { name: "Turquía" },
  { name: "Ucrania" },
];
